FROM ros:humble-ros-base

# =========================================================
# =========================================================

# Are you are looking for how to use this docker file?
#   - https://docs.openvins.com/dev-docker.html
#   - https://docs.docker.com/get-started/
#   - http://wiki.ros.org/docker/Tutorials/Docker

# =========================================================
# =========================================================

# Dependencies we use, catkin tools is very good build system
# Also some helper utilities for fast in terminal edits (nano etc)
RUN apt-get update && apt-get install -y libeigen3-dev nano git libopencv-dev libopencv-contrib-dev libboost-all-dev \
    ros-humble-cv-bridge ros-humble-image-transport ros-humble-message-filters

# Ceres solver install and setup
RUN apt-get install -y cmake libgoogle-glog-dev libgflags-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev libceres-dev

# Seems this has Python 3.10 installed on it...
RUN apt-get update && apt-get install -y python3-dev python3-matplotlib python3-numpy python3-psutil python3-tk

# Install deps needed for clion remote debugging
# https://blog.jetbrains.com/clion/2020/01/using-docker-with-clion/
RUN apt-get update && apt-get install -y ssh build-essential gcc g++ \
    gdb clang cmake rsync tar python3 && apt-get clean
RUN ( \
    echo 'LogLevel DEBUG2'; \
    echo 'PermitRootLogin yes'; \
    echo 'PasswordAuthentication yes'; \
    echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
  ) > /etc/ssh/sshd_config_test_clion \
  && mkdir /run/sshd
RUN useradd -m user && yes password | passwd user
RUN usermod -s /bin/bash user

# Build the ROS2 workspace
WORKDIR /ros2_ws
COPY ov_core      src/ov_core/
COPY ov_init      src/ov_init/
COPY ov_msckf     src/ov_msckf/
COPY ov_eval      src/ov_eval/
COPY config       src/config/
RUN apt-get update && \
    rosdep update && \
    . /opt/ros/humble/setup.sh && \
    rosdep install --from-paths src --ignore-src -r -y && \
    rm -rf /var/lib/apt/lists/*
RUN . /opt/ros/humble/setup.sh && \
    colcon build --symlink-install --event-handlers console_direct+ \
        --cmake-args -DCMAKE_BUILD_TYPE=Release

# Source the built workspace in all bash sessions and in the ROS entrypoint
RUN echo "source /ros2_ws/install/setup.bash" >> ~/.bashrc && \
    sed -i '/exec "\$@"/i source /ros2_ws/install/setup.bash' /ros_entrypoint.sh

CMD ["/bin/bash"]
