# Find more information about the parameters and the stereo pipeline here:
# https://docs.luxonis.com/software-v3/depthai/ros/parameters
# https://deepwiki.com/luxonis/depthai-ros/4.4.1-stereo-processing

oak:
  ros__parameters:
    camera:
      i_pipeline_type: 'Stereo'
      i_nn_type: none
      i_enable_imu: true

    left:
      i_publish_topic: true
      i_resolution: '400P'  # was 15
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50

    right:
      i_publish_topic: true
      i_resolution: '400P'
      i_fps: 5.0                
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50

    stereo:
      i_publish_topic: true
      i_output_disparity: false
      i_align_depth: false
      i_left_rect_publish_topic: true
      i_right_rect_publish_topic: true
      i_publish_synced_rect_pair: true
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
      i_subpixel: false
      i_lr_check: true
      i_stereo_conf_threshold: 200
      i_enable_decimation_filter: true
      i_depth_preset: 'HIGH_ACCURACY'

    imu:
      i_max_q_size: 30
      i_acc_freq: 100
      i_gyro_freq: 100
      i_enable_rotation: false