oak:
  ros__parameters:
    camera:
      i_pipeline_type: RGBD

    left:
      i_publish_topic: true
      i_fps: 10.0
      i_resolution: 400P

    right:
      i_publish_topic: true
      i_fps: 10.0
      i_resolution: 400P

    stereo:
      i_publish_topic: true
      i_subpixel: true
      i_stereo_conf_threshold: 110
      i_publish_left_rect: true
      i_publish_right_rect: true

    imu:
      i_publish_topic: true
      i_imu_frequency: 400
